{
 "title": "Node.js dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "cpu_usage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Open fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "process_open_fds",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}",
     "measurement": "open_fds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active handles",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "nodejs_active_handles_total",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "nodejs_active_handles_total-{{instance}}",
     "measurement": "active_handlles",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host-external",
     "expr": "nodejs_heap_space_size_used_bytes{space=\"new\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-new",
     "measurement": "memory_external",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_host-heapTotal",
     "expr": "nodejs_heap_space_size_used_bytes{space=\"old\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-old",
     "measurement": "memory_heapTotal",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_host-heapUsed",
     "expr": "nodejs_heap_space_size_used_bytes{space=\"code\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-code",
     "measurement": "memory_heapUsed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "$tag_host-rss",
     "expr": "nodejs_heap_space_size_used_bytes{space=\"map\"}",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{instance}}-map",
     "measurement": "memory_rss",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "expr": "nodejs_active_requests_total",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "nodejs_active_requests_total-{{instance}}",
     "measurement": "active_requests",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node.js version",
   "type": "table",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 8 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "nodejs_version",
     "query": "SELECT last(\"value\") AS \"alias\" FROM \"autogen\".\"nodejs_version\" WHERE $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "alias" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "V8 version",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 8 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "v8_version",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max fds",
   "type": "table",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "max_fds",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "event_loop",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}